### DataFrame 합치기

In [1]:
import pandas as pd
url='https://github.com/sehakflower/data/blob/main/titanic_1309.xlsx?raw=true'
titanic=pd.read_excel(url, sheet_name='total')
titanic

,pclass,survived,name,sex,age,sibsp,parch,ticket,fare,cabin,embarked,boat,body,home.dest
0,1,1,"Allen, Miss. Elisabeth Walton",female,29.0000,0,0,24160,211.3375,B5,S,2,NaN,"St Louis, MO"
1,1,1,"Allison, Master. Hudson Trevor",male,0.9167,1,2,113781,151.5500,C22 C26,S,11,NaN,"Montreal, PQ / Chesterville, ON"
2,1,0,"Allison, Miss. Helen Loraine",female,2.0000,1,2,113781,151.5500,C22 C26,S,NaN,NaN,"Montreal, PQ / Chesterville, ON"
3,1,0,"Allison, Mr. Hudson Joshua Creighton",male,30.0000,1,2,113781,151.5500,C22 C26,S,NaN,135.0,"Montreal, PQ / Chesterville, ON"
4,1,0,"Allison, Mrs. Hudson J C (Bessie Waldo Daniels)",female,25.0000,1,2,113781,151.5500,C22 C26,S,NaN,NaN,"Montreal, PQ / Chesterville, ON"
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1304,3,0,"Zabour, Miss. Hileni",female,14.5000,1,0,2665,14.4542,NaN,C,NaN,328.0,NaN
1305,3,0,"Zabour, Miss. Thamine",female,NaN,1,0,2665,14.4542,NaN,C,NaN,NaN,NaN
1306,3,0,"Zakarian, Mr. Mapriededer",male,26.5000,0,0,2656,7.2250,NaN,C,NaN,304.0,NaN
1307,3,0,"Zakarian, Mr. Ortin",male,27.0000,0,0,2670,7.2250,NaN,C,NaN,NaN,NaN
1308,3,0,"Zimmerman, Mr. Leo",male,29.0000,0,0,315082,7.8750,NaN,S,NaN,NaN,NaN

In [2]:
train_1000=titanic.iloc[:1000]
test_309=titanic.iloc[1000:]
len(train_1000), len(test_309)

(1000, 309)

SyntaxError: invalid syntax (663834132.py, line 1)

In [3]:
train_1000.to_csv('train_1000.csv')
test_309.to_csv('test_309.csv')

In [4]:
!pwd 
#!ls

/Users/ismoil/Desktop/bigdata

In [5]:
pd.read_csv('train_1000.csv')

,Unnamed: 0,pclass,survived,name,sex,age,sibsp,parch,ticket,fare,cabin,embarked,boat,body,home.dest
0,0,1,1,"Allen, Miss. Elisabeth Walton",female,29.0000,0,0,24160,211.3375,B5,S,2,NaN,"St Louis, MO"
1,1,1,1,"Allison, Master. Hudson Trevor",male,0.9167,1,2,113781,151.5500,C22 C26,S,11,NaN,"Montreal, PQ / Chesterville, ON"
2,2,1,0,"Allison, Miss. Helen Loraine",female,2.0000,1,2,113781,151.5500,C22 C26,S,NaN,NaN,"Montreal, PQ / Chesterville, ON"
3,3,1,0,"Allison, Mr. Hudson Joshua Creighton",male,30.0000,1,2,113781,151.5500,C22 C26,S,NaN,135.0,"Montreal, PQ / Chesterville, ON"
4,4,1,0,"Allison, Mrs. Hudson J C (Bessie Waldo Daniels)",female,25.0000,1,2,113781,151.5500,C22 C26,S,NaN,NaN,"Montreal, PQ / Chesterville, ON"
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
995,995,3,0,"Markoff, Mr. Marin",male,35.0000,0,0,349213,7.8958,NaN,C,NaN,NaN,NaN
996,996,3,0,"Markun, Mr. Johann",male,33.0000,0,0,349257,7.8958,NaN,S,NaN,NaN,NaN
997,997,3,1,"Masselmani, Mrs. Fatima",female,NaN,0,0,2649,7.2250,NaN,C,C,NaN,NaN
998,998,3,0,"Matinoff, Mr. Nicola",male,NaN,0,0,349255,7.8958,NaN,C,NaN,NaN,NaN
999,999,3,1,"McCarthy, Miss. Catherine ""Katie""",female,NaN,0,0,383123,7.7500,NaN,Q,15 16,NaN,NaN

In [47]:
### data 합치기:   concat

# total_df=pd.concat([train_1000, test_309]) # 옵션 없으면 axis=0
total_df=pd.concat([train_1000, test_309], axis=0) # 위아래로 붙일 때는 axis=0
total_df

,pclass,survived,name,sex,age,sibsp,parch,ticket,fare,cabin,embarked,boat,body,home.dest
0,1,1,"Allen, Miss. Elisabeth Walton",female,29.0000,0,0,24160,211.3375,B5,S,2,NaN,"St Louis, MO"
1,1,1,"Allison, Master. Hudson Trevor",male,0.9167,1,2,113781,151.5500,C22 C26,S,11,NaN,"Montreal, PQ / Chesterville, ON"
2,1,0,"Allison, Miss. Helen Loraine",female,2.0000,1,2,113781,151.5500,C22 C26,S,NaN,NaN,"Montreal, PQ / Chesterville, ON"
3,1,0,"Allison, Mr. Hudson Joshua Creighton",male,30.0000,1,2,113781,151.5500,C22 C26,S,NaN,135.0,"Montreal, PQ / Chesterville, ON"
4,1,0,"Allison, Mrs. Hudson J C (Bessie Waldo Daniels)",female,25.0000,1,2,113781,151.5500,C22 C26,S,NaN,NaN,"Montreal, PQ / Chesterville, ON"
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1304,3,0,"Zabour, Miss. Hileni",female,14.5000,1,0,2665,14.4542,NaN,C,NaN,328.0,NaN
1305,3,0,"Zabour, Miss. Thamine",female,NaN,1,0,2665,14.4542,NaN,C,NaN,NaN,NaN
1306,3,0,"Zakarian, Mr. Mapriededer",male,26.5000,0,0,2656,7.2250,NaN,C,NaN,304.0,NaN
1307,3,0,"Zakarian, Mr. Ortin",male,27.0000,0,0,2670,7.2250,NaN,C,NaN,NaN,NaN
1308,3,0,"Zimmerman, Mr. Leo",male,29.0000,0,0,315082,7.8750,NaN,S,NaN,NaN,NaN

In [43]:
total_df=pd.concat([train_1000, test_309])
total_df=pd.concat([train_1000, test_309], axis=1)
total_df

,pclass,survived,name,sex,age,sibsp,parch,ticket,fare,cabin,...,age,sibsp,parch,ticket,fare,cabin,embarked,boat,body,home.dest
0,1.0,1.0,"Allen, Miss. Elisabeth Walton",female,29.0000,0.0,0.0,24160,211.3375,B5,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,1.0,1.0,"Allison, Master. Hudson Trevor",male,0.9167,1.0,2.0,113781,151.5500,C22 C26,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,1.0,0.0,"Allison, Miss. Helen Loraine",female,2.0000,1.0,2.0,113781,151.5500,C22 C26,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,1.0,0.0,"Allison, Mr. Hudson Joshua Creighton",male,30.0000,1.0,2.0,113781,151.5500,C22 C26,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,1.0,0.0,"Allison, Mrs. Hudson J C (Bessie Waldo Daniels)",female,25.0000,1.0,2.0,113781,151.5500,C22 C26,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1304,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,14.5,1.0,0.0,2665,14.4542,NaN,C,NaN,328.0,NaN
1305,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,1.0,0.0,2665,14.4542,NaN,C,NaN,NaN,NaN
1306,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,26.5,0.0,0.0,2656,7.2250,NaN,C,NaN,304.0,NaN
1307,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,27.0,0.0,0.0,2670,7.2250,NaN,C,NaN,NaN,NaN
1308,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,29.0,0.0,0.0,315082,7.8750,NaN,S,NaN,NaN,NaN

In [8]:
##### data merge: 
## column 을 기준으로 결합
## merge 는 SQL 문의 JOIN 과 비슷  SELECT * FROM df1 INNER JOIN df2 ON df1.key = df2.key


df1=train_1000[['name', 'pclass', 'sex', 'age']]
df1

df2=train_1000[['name', 'survived']]
df2

## 일치 하는 column 이 없으면 error
#df2=train_1000[['survived']]
#df2

merge_inner=pd.merge(df1, df2)
merge_inner

,name,pclass,sex,age,survived
0,"Allen, Miss. Elisabeth Walton",1,female,29.0000,1
1,"Allison, Master. Hudson Trevor",1,male,0.9167,1
2,"Allison, Miss. Helen Loraine",1,female,2.0000,0
3,"Allison, Mr. Hudson Joshua Creighton",1,male,30.0000,0
4,"Allison, Mrs. Hudson J C (Bessie Waldo Daniels)",1,female,25.0000,0
...,...,...,...,...,...
999,"Markoff, Mr. Marin",3,male,35.0000,0
1000,"Markun, Mr. Johann",3,male,33.0000,0
1001,"Masselmani, Mrs. Fatima",3,female,NaN,1
1002,"Matinoff, Mr. Nicola",3,male,NaN,0
1003,"McCarthy, Miss. Catherine ""Katie""",3,female,NaN,1

In [53]:
# df2.loc[[0,2,3], ['name']] = ''       # 0,2,3 index 의 name 을 ''  으로 
# df2=df2[:10]

df1=df1[:10]
# merge_inner=pd.merge(df1, df2, how='inner', on='name')
merge_inner

#df2

,name,pclass,sex,age,survived
0,,NaN,NaN,NaN,1.0
1,,NaN,NaN,NaN,0.0
2,,NaN,NaN,NaN,0.0
3,"Allen, Miss. Elisabeth Walton",1.0,female,29.0000,NaN
4,"Allison, Master. Hudson Trevor",1.0,male,0.9167,1.0
5,"Allison, Miss. Helen Loraine",1.0,female,2.0000,NaN
6,"Allison, Mr. Hudson Joshua Creighton",1.0,male,30.0000,NaN
7,"Allison, Mrs. Hudson J C (Bessie Waldo Daniels)",1.0,female,25.0000,0.0
8,"Anderson, Mr. Harry",1.0,male,48.0000,1.0
9,"Andrews, Miss. Kornelia Theodosia",1.0,female,63.0000,1.0
10,"Andrews, Mr. Thomas Jr",1.0,male,39.0000,0.0
11,"Appleton, Mrs. Edward Dale (Charlotte Lamson)",1.0,female,53.0000,1.0
12,"Artagaveytia, Mr. Ramon",1.0,male,71.0000,0.0

In [10]:
df1=df1[:10]
df1

                                              name  pclass     sex      age
0                    Allen, Miss. Elisabeth Walton       1  female  29.0000
1                   Allison, Master. Hudson Trevor       1    male   0.9167
2                     Allison, Miss. Helen Loraine       1  female   2.0000
3             Allison, Mr. Hudson Joshua Creighton       1    male  30.0000
4  Allison, Mrs. Hudson J C (Bessie Waldo Daniels)       1  female  25.0000
5                              Anderson, Mr. Harry       1    male  48.0000
6                Andrews, Miss. Kornelia Theodosia       1  female  63.0000
7                           Andrews, Mr. Thomas Jr       1    male  39.0000
8    Appleton, Mrs. Edward Dale (Charlotte Lamson)       1  female  53.0000
9                          Artagaveytia, Mr. Ramon       1    male  71.0000

In [11]:
#inner: 두 DataFrame 에서 교집합. outer:  합집합 (한곳에만 있어도 됨).  left(왼쪽에 있는것 기준), right 
#on:  이 column 이 기준점 
merge_inner=pd.merge(df1, df2, how='inner', on='name')     
merge_inner=pd.merge(df1, df2, how='outer', on='name')    

merge_inner

,name,pclass,sex,age,survived
0,,NaN,NaN,NaN,1.0
1,,NaN,NaN,NaN,0.0
2,,NaN,NaN,NaN,0.0
3,"Allen, Miss. Elisabeth Walton",1.0,female,29.0000,NaN
4,"Allison, Master. Hudson Trevor",1.0,male,0.9167,1.0
5,"Allison, Miss. Helen Loraine",1.0,female,2.0000,NaN
6,"Allison, Mr. Hudson Joshua Creighton",1.0,male,30.0000,NaN
7,"Allison, Mrs. Hudson J C (Bessie Waldo Daniels)",1.0,female,25.0000,0.0
8,"Anderson, Mr. Harry",1.0,male,48.0000,1.0
9,"Andrews, Miss. Kornelia Theodosia",1.0,female,63.0000,1.0
10,"Andrews, Mr. Thomas Jr",1.0,male,39.0000,0.0
11,"Appleton, Mrs. Edward Dale (Charlotte Lamson)",1.0,female,53.0000,1.0
12,"Artagaveytia, Mr. Ramon",1.0,male,71.0000,0.0

In [12]:
merge_left=pd.merge(df1, df2, how='left', left_on='name', right_on='name')

#merge_left=pd.merge(df2, df1, how='left', left_on='name', right_on='name')

#merge_left=pd.merge(df1, df2, how='right', left_on='name', right_on='name')
merge_left

,name,pclass,sex,age,survived
0,"Allen, Miss. Elisabeth Walton",1,female,29.0000,NaN
1,"Allison, Master. Hudson Trevor",1,male,0.9167,1.0
2,"Allison, Miss. Helen Loraine",1,female,2.0000,NaN
3,"Allison, Mr. Hudson Joshua Creighton",1,male,30.0000,NaN
4,"Allison, Mrs. Hudson J C (Bessie Waldo Daniels)",1,female,25.0000,0.0
5,"Anderson, Mr. Harry",1,male,48.0000,1.0
6,"Andrews, Miss. Kornelia Theodosia",1,female,63.0000,1.0
7,"Andrews, Mr. Thomas Jr",1,male,39.0000,0.0
8,"Appleton, Mrs. Edward Dale (Charlotte Lamson)",1,female,53.0000,1.0
9,"Artagaveytia, Mr. Ramon",1,male,71.0000,0.0

In [13]:
###### DataFrame 결합:  join
## index 를 기준으로 두 DataFrame 을 합칠때 사용
## how='left' 가  기본값  (왼쪽 DataFrame 의 행 index 를 보존하면서 데이터를 붙임)

In [14]:
df2.loc[[1], ['name']]='Kildong, Mr. Hong'
df2=df2[:10]
df2

                                              name  survived
0                                                          1
1                                Kildong, Mr. Hong         1
2                                                          0
3                                                          0
4  Allison, Mrs. Hudson J C (Bessie Waldo Daniels)         0
5                              Anderson, Mr. Harry         1
6                Andrews, Miss. Kornelia Theodosia         1
7                           Andrews, Mr. Thomas Jr         0
8    Appleton, Mrs. Edward Dale (Charlotte Lamson)         1
9                          Artagaveytia, Mr. Ramon         0

In [15]:
df1.set_index('name', inplace=True)
df2.set_index('name', inplace=True)

In [16]:
df1.join(df2)
#df1

,pclass,sex,age,survived
name,,,,
"Allen, Miss. Elisabeth Walton",1,female,29.0000,NaN
"Allison, Master. Hudson Trevor",1,male,0.9167,NaN
"Allison, Miss. Helen Loraine",1,female,2.0000,NaN
"Allison, Mr. Hudson Joshua Creighton",1,male,30.0000,NaN
"Allison, Mrs. Hudson J C (Bessie Waldo Daniels)",1,female,25.0000,0.0
"Anderson, Mr. Harry",1,male,48.0000,1.0
"Andrews, Miss. Kornelia Theodosia",1,female,63.0000,1.0
"Andrews, Mr. Thomas Jr",1,male,39.0000,0.0
"Appleton, Mrs. Edward Dale (Charlotte Lamson)",1,female,53.0000,1.0
"Artagaveytia, Mr. Ramon",1,male,71.0000,0.0

In [17]:
df1.join(df2, how='inner')

,pclass,sex,age,survived
name,,,,
"Allison, Mrs. Hudson J C (Bessie Waldo Daniels)",1,female,25.0,0
"Anderson, Mr. Harry",1,male,48.0,1
"Andrews, Miss. Kornelia Theodosia",1,female,63.0,1
"Andrews, Mr. Thomas Jr",1,male,39.0,0
"Appleton, Mrs. Edward Dale (Charlotte Lamson)",1,female,53.0,1
"Artagaveytia, Mr. Ramon",1,male,71.0,0

In [18]:
df2.join(df1)

,survived,pclass,sex,age
name,,,,
,1,NaN,NaN,NaN
"Kildong, Mr. Hong",1,NaN,NaN,NaN
,0,NaN,NaN,NaN
,0,NaN,NaN,NaN
"Allison, Mrs. Hudson J C (Bessie Waldo Daniels)",0,1.0,female,25.0
"Anderson, Mr. Harry",1,1.0,male,48.0
"Andrews, Miss. Kornelia Theodosia",1,1.0,female,63.0
"Andrews, Mr. Thomas Jr",0,1.0,male,39.0
"Appleton, Mrs. Edward Dale (Charlotte Lamson)",1,1.0,female,53.0
"Artagaveytia, Mr. Ramon",0,1.0,male,71.0

In [19]:
####  조건 검색으로 data 추출

url='https://raw.githubusercontent.com/sehakflower/data/main/titanic.csv'
titanic_df=pd.read_csv(url,sep='\t')
titanic_df

new_columns=['passengerId', 'survived', 'pclass', 'name', 'sex', 'age', 'sibsp', 'parch','ticket', 'fare', 'cabin', 'embarked']
titanic_df.columns=new_columns
titanic_df.columns

Index(['passengerId', 'survived', 'pclass', 'name', 'sex', 'age', 'sibsp',
       'parch', 'ticket', 'fare', 'cabin', 'embarked'],
      dtype='str')

In [20]:
#titanic_df[titanic_df['age']>70] # 70세 이상인 승객 검색
#titanic_df[titanic_df['age']>70][['name', 'age']] # 70세 이상인 승객 검색
titanic_df[titanic_df['age']<3] # 3세 미만 승객의 이름 검색

,passengerId,survived,pclass,name,sex,age,sibsp,parch,ticket,fare,cabin,embarked
7,8,0,3,"Palsson, Master. Gosta Leonard",male,2.00,3,1,349909,21.075,NaN,S
16,17,0,3,"Rice, Master. Eugene",male,2.00,4,1,382652,29.125,NaN,Q
78,79,1,2,"Caldwell, Master. Alden Gates",male,0.83,0,2,248738,29.000,NaN,S
119,120,0,3,"Andersson, Miss. Ellis Anna Maria",female,2.00,4,2,347082,31.275,NaN,S

In [21]:
titanic_df.loc[titanic_df['age']<3]['name'] # 3세 미만 승객의 이름 검색

7         Palsson, Master. Gosta Leonard
16                  Rice, Master. Eugene
78         Caldwell, Master. Alden Gates
119    Andersson, Miss. Ellis Anna Maria
Name: name, dtype: str

In [22]:
titanic_df.loc[titanic_df['age']<3, 'name':'ticket']

                                  name     sex   age  sibsp  parch  ticket
7       Palsson, Master. Gosta Leonard    male  2.00      3      1  349909
16                Rice, Master. Eugene    male  2.00      4      1  382652
78       Caldwell, Master. Alden Gates    male  0.83      0      2  248738
119  Andersson, Miss. Ellis Anna Maria  female  2.00      4      2  347082

In [23]:
#### isin 함수로 조건 검색

In [ ]:
my_condition=['male']

my_condition

['male']

In [25]:
titanic_df['sex'].isin(my_condition)

0       True
1      False
2      False
3      False
4       True
       ...
151    False
152     True
153     True
154     True
155     True
Name: sex, Length: 156, dtype: bool

In [60]:
my_condition1=['Molly Brown']
my_condition1

['Molly Brown']

In [61]:
titanic_df['name'].isin(my_condition1)

0      False
1      False
2      False
3      False
4      False
       ...
151    False
152    False
153    False
154    False
155    False
Name: name, Length: 156, dtype: bool

In [28]:
titanic_df.loc[titanic_df['name'].isin(my_condition1)]

,passengerId,survived,pclass,name,sex,age,sibsp,parch,ticket,fare,cabin,embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
155,156,0,1,"Williams, Mr. Charles Duane",male,51.0,0,1,PC 17597,61.3792,NaN,C

In [29]:
titanic_df.loc[titanic_df['name'].isin(my_condition1), 'age']
#titanic_df.loc[titanic_df['name'].isin(my_condition1), 'pclass':'age']

0      22.0
155    51.0
Name: age, dtype: float64

In [62]:
titanic_df.loc[titanic_df['name'] >'', 'age']

0      22.0
1      38.0
2      26.0
3      35.0
4      35.0
       ...
151    22.0
152    55.5
153    40.5
154     NaN
155    51.0
Name: age, Length: 156, dtype: float64

In [31]:
#####  검색 정보를 활용해 타이타닉 승객 구분하기

In [32]:
titanic_df['name'][0]
#titanic_df['name'][0].split(',')[1]
#titanic_df['name'][0].split(',')[1].split('.')[0].strip( )

'Braund, Mr. Owen Harris'

In [33]:
test=lambda x: x+2
test(2)
range(5) # 0, 1, 2, 3, 4

range(0, 5)

In [34]:
list(map(test, range(5)))

[2, 3, 4, 5, 6]

In [35]:
condition=lambda x: x.split(',')[1].split('.')[0].strip( )
titanic_df['title']=titanic_df['name'].map(condition)
titanic_df['title']

titanic_df[0:10]

,passengerId,survived,pclass,name,sex,age,sibsp,parch,ticket,fare,cabin,embarked,title
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S,Mr
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C,Mrs
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S,Miss
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S,Mrs
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S,Mr
5,6,0,3,"Moran, Mr. James",male,NaN,0,0,330877,8.4583,NaN,Q,Mr
6,7,0,1,"McCarthy, Mr. Timothy J",male,54.0,0,0,17463,51.8625,E46,S,Mr
7,8,0,3,"Palsson, Master. Gosta Leonard",male,2.0,3,1,349909,21.0750,NaN,S,Master
8,9,1,3,"Johnson, Mrs. Oscar W (Elisabeth Vilhelmina Berg)",female,27.0,0,2,347742,11.1333,NaN,S,Mrs
9,10,1,2,"Nasser, Mrs. Nicholas (Adele Achem)",female,14.0,1,0,237736,30.0708,NaN,C,Mrs

In [36]:
titles=titanic_df['title'].unique( )
titles

<StringArray>
['Mr', 'Mrs', 'Miss', 'Master', 'Don', 'Rev']
Length: 6, dtype: str

In [37]:
#  두 factor (요인) 간의 빈도 수를 보여 줌
pd.crosstab( titanic_df['title'], titanic_df['sex'])
#pd.crosstab( titanic_df['title'], titanic_df['sex'], normalize='all')

sex     female  male
title
Don          0     1
Master       0     8
Miss        34     0
Mr           0    89
Mrs         22     0
Rev          0     2

In [38]:
Special=[ 'Master', 'Don', 'Rev']
for each in Special:
  titanic_df['title']=titanic_df['title'].replace(each, 'Special')
  
titanic_df['title'].unique( )

<StringArray>
['Mr', 'Mrs', 'Miss', 'Special']
Length: 4, dtype: str

In [39]:
print(titanic_df[['title', 'survived']].groupby(['title'], as_index=True).mean( ))
print(titanic_df[['title', 'survived']].groupby(['title'], as_index=False).mean( ))

         survived
title
Miss     0.705882
Mr       0.123596
Mrs      0.727273
Special  0.272727
     title  survived
0     Miss  0.705882
1       Mr  0.123596
2      Mrs  0.727273
3  Special  0.272727