### Python 에서 피일 처리

In [3]:
f=open('file.txt', 'rt', encoding='UTF8')
for line in f:
    print(line, end="")         # print 함수가 자동으로 '\n' 을 붙이는것을 방지
    #print(line)

f.close()

작은 일에 성실한 사람은 큰 일에도 성실하고,
작은 일에 정직하지 못한 사람은 큰 일에도 정직하지 못하다.
누가복음 16:10

변함없이 서로 사랑하는 이가 친구이며
위급할 때 서로 돕는 이가 형제이다.
잠언 17:17

In [4]:
## newline=''  :  읽어 올때 줄바꿈 문자를 임의로 변경하지 말고 그대로 읽어라
## windows: \r\n,  linux(mac): \n   임.   
## python 은  \r\n or \n  ==> \n 으로 변환해서 읽음(default 동작)  

with open("proverb.txt",'r', encoding='UTF8', newline='') as filereader:
  for row in filereader:
    print("{}".format(row.strip( )))      # strip 을 통해 양끝의 공백 및 \n 을 제거
    #print(row)

작은 일에 성실한 사람은 큰 일에도 성실하고,
작은 일에 정직하지 못한 사람은 큰 일에도 정직하지 못하다.
누가복음 16:10

변함없이 서로 사랑하는 이가 친구이며
위급할 때 서로 돕는 이가 형제이다.
잠언 17:17

In [5]:
# glob이라는 이름은 **Unix shell의 "globbing"**에서 왔다.
# glob module finds pathnames matching a specified pattern

import os
import glob     

for file in glob.glob(os.path.join('*.txt')):
  with open(file, 'r', newline='',encoding='UTF8') as filereader:
    for row in filereader:
      print("{}".format(row.strip( )))

작은 일에 성실한 사람은 큰 일에도 성실하고,
작은 일에 정직하지 못한 사람은 큰 일에도 정직하지 못하다.
누가복음 16:10

변함없이 서로 사랑하는 이가 친구이며
위급할 때 서로 돕는 이가 형제이다.
잠언 17:17
작은 일에 성실한 사람은 큰 일에도 성실하고,
작은 일에 정직하지 못한 사람은 큰 일에도 정직하지 못하다.
누가복음 16:10

변함없이 서로 사랑하는 이가 친구이며
위급할 때 서로 돕는 이가 형제이다.
잠언 17:17

In [6]:
b1=" 작은 일에 성실한 사람은      큰일에도 성실하고 "
b1.strip( ) # 공백 제거

# text="....작은 일에 성실한 사람은, 큰일에도 성실하고...."
# print(text.lstrip('.'))
# print(text.rstrip('.'))
# print(text.strip('.'))

'작은 일에 성실한 사람은      큰일에도 성실하고'

In [7]:
text="....작은 일에,성실한 사람은, 큰일에도,  성실하고...."
print(text.split(", "))

['....작은 일에,성실한 사람은', '큰일에도', ' 성실하고....']

In [8]:
%pip install pandas

/Users/ismoil/Desktop/bigdata/.venv/bin/python: No module named pip
Note: you may need to restart the kernel to use updated packages.

In [9]:
## web 에서 csv 가져 오기

import pandas as pd
titanic_df=pd.read_csv('https://raw.githubusercontent.com/sehakflower/data/main/titanic.csv')
titanic_df

                        PassengerId\tSurvived\tPclass\tName\tSex\tAge\tSibSp\tParch\tTicket\tFare\tCabin\tEmbarked
1\t0\t3\tBraund           Mr. Owen Harris\tmale\t22\t1\t0\tA/5 21171\t7...
2\t1\t1\tCumings          Mrs. John Bradley (Florence Briggs Thayer)\tf...
3\t1\t3\tHeikkinen        Miss. Laina\tfemale\t26\t0\t0\tSTON/O2. 31012...
4\t1\t1\tFutrelle         Mrs. Jacques Heath (Lily May Peel)\tfemale\t3...
5\t0\t3\tAllen            Mr. William Henry\tmale\t35\t0\t0\t373450\t8....
...                                                                    ...
152\t1\t1\tPears          Mrs. Thomas (Edith Wearne)\tfemale\t22\t1\t0\...
153\t0\t3\tMeo            Mr. Alfonzo\tmale\t55.5\t0\t0\tA.5. 11206\t8....
154\t0\t3\tvan Billiard   Mr. Austin Blyler\tmale\t40.5\t0\t2\tA/5. 851...
155\t0\t3\tOlsen          Mr. Ole Martin\tmale\t\t0\t0\tFa 265302\t7.31...
156\t0\t1\tWilliams       Mr. Charles Duane\tmale\t51\t0\t1\tPC 17597\t...

[156 rows x 1 columns]

In [10]:
# tab 으로 분리
url='https://raw.githubusercontent.com/sehakflower/data/main/titanic.csv'
titanic_df=pd.read_csv(url,sep='\t')
titanic_df

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S
...,...,...,...,...,...,...,...,...,...,...,...,...
151,152,1,1,"Pears, Mrs. Thomas (Edith Wearne)",female,22.0,1,0,113776,66.6000,C2,S
152,153,0,3,"Meo, Mr. Alfonzo",male,55.5,0,0,A.5. 11206,8.0500,NaN,S
153,154,0,3,"van Billiard, Mr. Austin Blyler",male,40.5,0,2,A/5. 851,14.5000,NaN,S
154,155,0,3,"Olsen, Mr. Ole Martin",male,NaN,0,0,Fa 265302,7.3125,NaN,S
155,156,0,1,"Williams, Mr. Charles Duane",male,51.0,0,1,PC 17597,61.3792,NaN,C

In [11]:
# excel file 가져 오기
titanic='https://github.com/sehakflower/data/blob/main/titanic.xlsx?raw=true'
titanic=pd.read_excel(titanic,sheet_name='titanic3')
titanic

,pclass,survived,name,sex,age,sibsp,parch,ticket,fare,cabin,embarked,boat,body,home.dest
0,1,1,"Allen, Miss. Elisabeth Walton",female,29.0000,0,0,24160,211.3375,B5,S,2,NaN,"St Louis, MO"
1,1,1,"Allison, Master. Hudson Trevor",male,0.9167,1,2,113781,151.5500,C22 C26,S,11,NaN,"Montreal, PQ / Chesterville, ON"
2,1,0,"Allison, Miss. Helen Loraine",female,2.0000,1,2,113781,151.5500,C22 C26,S,NaN,NaN,"Montreal, PQ / Chesterville, ON"
3,1,0,"Allison, Mr. Hudson Joshua Creighton",male,30.0000,1,2,113781,151.5500,C22 C26,S,NaN,135.0,"Montreal, PQ / Chesterville, ON"
4,1,0,"Allison, Mrs. Hudson J C (Bessie Waldo Daniels)",female,25.0000,1,2,113781,151.5500,C22 C26,S,NaN,NaN,"Montreal, PQ / Chesterville, ON"
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1304,3,0,"Zabour, Miss. Hileni",female,14.5000,1,0,2665,14.4542,NaN,C,NaN,328.0,NaN
1305,3,0,"Zabour, Miss. Thamine",female,NaN,1,0,2665,14.4542,NaN,C,NaN,NaN,NaN
1306,3,0,"Zakarian, Mr. Mapriededer",male,26.5000,0,0,2656,7.2250,NaN,C,NaN,304.0,NaN
1307,3,0,"Zakarian, Mr. Ortin",male,27.0000,0,0,2670,7.2250,NaN,C,NaN,NaN,NaN
1308,3,0,"Zimmerman, Mr. Leo",male,29.0000,0,0,315082,7.8750,NaN,S,NaN,NaN,NaN

In [12]:
#  head , tail 함수
titanic_df.head(7)
#titanic_df.tail(7)

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S
5,6,0,3,"Moran, Mr. James",male,NaN,0,0,330877,8.4583,NaN,Q
6,7,0,1,"McCarthy, Mr. Timothy J",male,54.0,0,0,17463,51.8625,E46,S

In [13]:
# len , shape
len(titanic_df)
#titanic_df.shape

156

In [14]:
## data 의 기본 통계치
titanic_df.describe( )

,PassengerId,Survived,Pclass,Age,SibSp,Parch,Fare
count,156.000000,156.000000,156.000000,126.000000,156.000000,156.000000,156.000000
mean,78.500000,0.346154,2.423077,28.141508,0.615385,0.397436,28.109587
std,45.177428,0.477275,0.795459,14.613880,1.056235,0.870146,39.401047
min,1.000000,0.000000,1.000000,0.830000,0.000000,0.000000,6.750000
25%,39.750000,0.000000,2.000000,19.000000,0.000000,0.000000,8.003150
50%,78.500000,0.000000,3.000000,26.000000,0.000000,0.000000,14.454200
75%,117.250000,1.000000,3.000000,35.000000,1.000000,0.000000,30.371850
max,156.000000,1.000000,3.000000,71.000000,5.000000,5.000000,263.000000

In [15]:
titanic_df.info( )

<class 'pandas.DataFrame'>
RangeIndex: 156 entries, 0 to 155
Data columns (total 12 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   PassengerId  156 non-null    int64
 1   Survived     156 non-null    int64
 2   Pclass       156 non-null    int64
 3   Name         156 non-null    str
 4   Sex          156 non-null    str
 5   Age          126 non-null    float64
 6   SibSp        156 non-null    int64
 7   Parch        156 non-null    int64
 8   Ticket       156 non-null    str
 9   Fare         156 non-null    float64
 10  Cabin        31 non-null     str
 11  Embarked     155 non-null    str
dtypes: float64(2), int64(5), str(5)
memory usage: 14.8 KB

In [16]:
titanic_df.columns

Index(['PassengerId', 'Survived', 'Pclass', 'Name', 'Sex', 'Age', 'SibSp',
       'Parch', 'Ticket', 'Fare', 'Cabin', 'Embarked'],
      dtype='str')

In [17]:
new_columns=['passengerId', 'survived', 'pclass', 'name', 'sex', 'age', 'sibsp', 'parch',
'ticket', 'fare', 'cabin', 'embarked']
titanic_df.columns=new_columns
titanic_df.columns

Index(['passengerId', 'survived', 'pclass', 'name', 'sex', 'age', 'sibsp',
       'parch', 'ticket', 'fare', 'cabin', 'embarked'],
      dtype='str')

In [18]:
titanic_df

,passengerId,survived,pclass,name,sex,age,sibsp,parch,ticket,fare,cabin,embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S
...,...,...,...,...,...,...,...,...,...,...,...,...
151,152,1,1,"Pears, Mrs. Thomas (Edith Wearne)",female,22.0,1,0,113776,66.6000,C2,S
152,153,0,3,"Meo, Mr. Alfonzo",male,55.5,0,0,A.5. 11206,8.0500,NaN,S
153,154,0,3,"van Billiard, Mr. Austin Blyler",male,40.5,0,2,A/5. 851,14.5000,NaN,S
154,155,0,3,"Olsen, Mr. Ole Martin",male,NaN,0,0,Fa 265302,7.3125,NaN,S
155,156,0,1,"Williams, Mr. Charles Duane",male,51.0,0,1,PC 17597,61.3792,NaN,C

In [19]:
# 복사
copy_titanic_df=titanic_df.copy( )
copy_titanic_df.head( )

,passengerId,survived,pclass,name,sex,age,sibsp,parch,ticket,fare,cabin,embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S

In [20]:
# 행 추가 

#pandas version
print(pd.__version__)

# append 는 pandas 버전 2.0 부터 제거 됨.
# copy_titanic_df.append({'passengerId':1, 'survived':1, 'pclass':1, 'name':1, 'sex':1,
#     'age':1, 'sibsp':1, 'parch':1, 'ticket':1, 'fare':1, 'cabin':1, 'embarked':1}, ignore_index=True)


# 1. 추가할 데이터를 데이터프레임으로 만듭니다. (딕셔너리를 리스트로 감싸야 합니다)
new_row = pd.DataFrame([{
    'passengerId':1, 'survived':1, 'pclass':1, 'name':1, 'sex':1,
    'age':1, 'sibsp':1, 'parch':1, 'ticket':1, 'fare':1, 'cabin':1,
    'embarked':1
}])

## 2. pd.concat을 사용하여 합칩니다.
## ignore_index,  기존의 각 DataFrame 에 있는 index 를 무시 하고 새로 만들어라.
## pandas 는 기본적으로 index 가 중복되는것을 허용하기 때문에 나중에 중복된 index 가 생겨 버릴 위험이 있다.
#copy_titanic_df = pd.concat([copy_titanic_df, new_row], ignore_index=True)

## 마지막 인덱스 다음에 새 행 추가
copy_titanic_df.loc[len(copy_titanic_df)] = [1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1]

3.0.2

In [21]:
copy_titanic_df.tail()

,passengerId,survived,pclass,name,sex,age,sibsp,parch,ticket,fare,cabin,embarked
152,153,0,3,"Meo, Mr. Alfonzo",male,55.5,0,0,A.5. 11206,8.0500,NaN,S
153,154,0,3,"van Billiard, Mr. Austin Blyler",male,40.5,0,2,A/5. 851,14.5000,NaN,S
154,155,0,3,"Olsen, Mr. Ole Martin",male,NaN,0,0,Fa 265302,7.3125,NaN,S
155,156,0,1,"Williams, Mr. Charles Duane",male,51.0,0,1,PC 17597,61.3792,NaN,C
156,1,1,1,1,1,1.0,1,1,1,1.0000,1,1

In [22]:
# 열 추가 하기
copy_titanic_df['gender']=1
copy_titanic_df.tail( )

,passengerId,survived,pclass,name,sex,age,sibsp,parch,ticket,fare,cabin,embarked,gender
152,153,0,3,"Meo, Mr. Alfonzo",male,55.5,0,0,A.5. 11206,8.0500,NaN,S,1
153,154,0,3,"van Billiard, Mr. Austin Blyler",male,40.5,0,2,A/5. 851,14.5000,NaN,S,1
154,155,0,3,"Olsen, Mr. Ole Martin",male,NaN,0,0,Fa 265302,7.3125,NaN,S,1
155,156,0,1,"Williams, Mr. Charles Duane",male,51.0,0,1,PC 17597,61.3792,NaN,C,1
156,1,1,1,1,1,1.0,1,1,1,1.0000,1,1,1

In [23]:
#  "sex"  가 female 인 행들을 골라서( ['sex']=='female' )  gender = 0 으로 set 
copy_titanic_df.loc[copy_titanic_df['sex']=='female', 'gender']=0
copy_titanic_df.head( )

,passengerId,survived,pclass,name,sex,age,sibsp,parch,ticket,fare,cabin,embarked,gender
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S,1
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C,0
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S,0
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S,0
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S,1

In [24]:
#######   index 정리 하기

In [25]:
titanic_df.index

RangeIndex(start=0, stop=156, step=1)

In [26]:
titanic_df.values

array([[1, 0, 3, ..., 7.25, nan, 'S'],
       [2, 1, 1, ..., 71.2833, 'C85', 'C'],
       [3, 1, 3, ..., 7.925, nan, 'S'],
       ...,
       [154, 0, 3, ..., 14.5, nan, 'S'],
       [155, 0, 3, ..., 7.3125, nan, 'S'],
       [156, 0, 1, ..., 61.3792, nan, 'C']], shape=(156, 12), dtype=object)

In [27]:
## 열 추출하기
age=titanic_df['age'] # Series 객체는 1차원 배열(ndarray)과 호환됨
print(type(age))
age

<class 'pandas.Series'>

0      22.0
1      38.0
2      26.0
3      35.0
4      35.0
       ...
151    22.0
152    55.5
153    40.5
154     NaN
155    51.0
Name: age, Length: 156, dtype: float64

In [28]:
## 정렬하기
titanic_df.sort_index( )    # index 순으로 

# titanic_df.sort_values(by='age') # 오름차순 정렬
# titanic_df.sort_values(by='age', ascending=False) # 내림차순 정렬

# titanic_df.sort_values(by=['age', 'pclass']) # 오름차순 정렬
# titanic_df.sort_values(by=['age', 'pclass'], ascending=False) # 내림차순 정렬

,passengerId,survived,pclass,name,sex,age,sibsp,parch,ticket,fare,cabin,embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S
...,...,...,...,...,...,...,...,...,...,...,...,...
151,152,1,1,"Pears, Mrs. Thomas (Edith Wearne)",female,22.0,1,0,113776,66.6000,C2,S
152,153,0,3,"Meo, Mr. Alfonzo",male,55.5,0,0,A.5. 11206,8.0500,NaN,S
153,154,0,3,"van Billiard, Mr. Austin Blyler",male,40.5,0,2,A/5. 851,14.5000,NaN,S
154,155,0,3,"Olsen, Mr. Ole Martin",male,NaN,0,0,Fa 265302,7.3125,NaN,S
155,156,0,1,"Williams, Mr. Charles Duane",male,51.0,0,1,PC 17597,61.3792,NaN,C

In [29]:
titanic_df.head(5)

### pandas 에서 []  는   행이 아니라 열 에서 찾는다.  즉 column 을 찾을때 시용한다.
#titanic_df[0] # KeyError
#titanic_df[3,1] # KeyError             # DataFrame 에서는 [] 를 사용해서   행,열 을 표시 하지 못한다. 이 뜻은 column 이름이 이 (3,1) 인 컬럼을 찾아라
#titanic_df[3,:] # KeyError

,passengerId,survived,pclass,name,sex,age,sibsp,parch,ticket,fare,cabin,embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S

In [ ]:
# # titanic_df[0:5] # titanic_df.head(  )와 실행 결과 동일함
# titanic_df[0:1] # 첫 행만 가져오기
# titanic_df[::3] # 3개씩 건너서 출력함
# titanic_df[::-1] # 행의 순서를 거꾸로 출력함

,passengerId,survived,pclass,name,sex,age,sibsp,parch,ticket,fare,cabin,embarked
155,156,0,1,"Williams, Mr. Charles Duane",male,51.0,0,1,PC 17597,61.3792,NaN,C
154,155,0,3,"Olsen, Mr. Ole Martin",male,NaN,0,0,Fa 265302,7.3125,NaN,S
153,154,0,3,"van Billiard, Mr. Austin Blyler",male,40.5,0,2,A/5. 851,14.5000,NaN,S
152,153,0,3,"Meo, Mr. Alfonzo",male,55.5,0,0,A.5. 11206,8.0500,NaN,S
151,152,1,1,"Pears, Mrs. Thomas (Edith Wearne)",female,22.0,1,0,113776,66.6000,C2,S
...,...,...,...,...,...,...,...,...,...,...,...,...
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S

In [54]:
k = titanic_df[titanic_df.columns[0]] # 첫 번째(0번) 열을 1차원 배열의 Series 객체로 추출

s = titanic_df.columns[0]
# s
#type(s)

k
type(k)

pandas.Series

In [57]:
# titanic_df[titanic_df.columns[11]] # 마지막 열을 1차원 배열의 Series 객체로 추출
titanic_df[titanic_df.columns[-1]] # 혹은 [-1]로 표시

0      S
1      C
2      S
3      S
4      S
      ..
151    S
152    S
153    S
154    S
155    C
Name: embarked, Length: 156, dtype: str

In [33]:
# 열 이름으로 데이터 가져오기
age=titanic_df['age']
print(type(age))

<class 'pandas.Series'>

In [34]:
titanic_df['age'] # 'age' 열을 1차원 배열인 Series 객체로 추출
titanic_df.age

0      22.0
1      38.0
2      26.0
3      35.0
4      35.0
       ...
151    22.0
152    55.5
153    40.5
154     NaN
155    51.0
Name: age, Length: 156, dtype: float64

In [58]:
#열 이름과 위치를 이용해 데이터 가져오기

print(titanic_df[titanic_df.columns[0]][0]) # 첫 번째 열의 첫 번째 값
print(titanic_df['age'][0]) # age 열의 첫 번째 값
print(titanic_df[titanic_df.columns[0]][2])
print(titanic_df[titanic_df.columns[-1]][0])
type(titanic_df[titanic_df.columns[0]][0]) # str

1
22.0
3
S

numpy.int64

In [36]:
print(type(titanic_df.index))

print(titanic_df.index.dtype)

<class 'pandas.RangeIndex'>
int64

In [62]:
#### index 이름 를 기준으로 data 가져 오기

# titanic_df.loc[0]
# titanic_df.loc[0:5]
# titanic_df.loc[0:10:2]

#titanic_df.loc[:, 'age']
#titanic_df['age']

#titanic_df.loc[:, ['age', 'sex']]
#titanic_df[['age', 'sex']]

titanic_df.loc[3:7, ['age', 'sex']]
# titanic_df.loc[2:5, 'survived':'age']

    age     sex
3  35.0  female
4  35.0    male
5   NaN    male
6  54.0    male
7   2.0    male

In [66]:
#### index 순서를 기준으로 data 가져 오기

# titanic_df.iloc[0]

titanic_df.iloc[0:10:3]

#titanic_df.iloc[:, [0,3]]           # 모든 rows 의 0, 3번 째 column

#titanic_df.iloc[1:5, 1:4]

,passengerId,survived,pclass,name,sex,age,sibsp,parch,ticket,fare,cabin,embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
6,7,0,1,"McCarthy, Mr. Timothy J",male,54.0,0,0,17463,51.8625,E46,S
9,10,1,2,"Nasser, Mrs. Nicholas (Adele Achem)",female,14.0,1,0,237736,30.0708,NaN,C

In [39]:
### 피벗 테이블을 이용해 data 가져 오기

#titanic_df.pivot_table(index='pclass', columns='sex', values='survived')

titanic_df.pivot_table(index='pclass', columns='sex', values='survived', aggfunc='mean')

#titanic_df.pivot_table(index='pclass', columns='sex', values='survived', aggfunc='count')

# 성별/선실별 승객 수 (결측치 제외)
#titanic_df.pivot_table(index='pclass', columns='sex', values='survived', aggfunc='count')
#titanic_df.pivot_table(index='pclass', columns='sex', values='survived', aggfunc=['mean', 'count'])

sex       female      male
pclass
1       1.000000  0.142857
2       0.916667  0.166667
3       0.571429  0.131148

In [40]:
# 주피터 노트북 사용자
# %pip install numpy

In [69]:
## group 으로 묶어서 data 가져 오기
titanic_df.groupby('survived').count()
# titanic_df.groupby('survived')

#titanic_df.groupby('survived').mean()     # error

# 숫자형 데이터가 있는 컬럼만 골라서 평균을 구함
# titanic_df.groupby('survived').mean(numeric_only=True)

#df2 = titanic_df.astype({'survived': 'int', '컬럼B': 'float'})      # error
#df2 = titanic_df.astype({'survived': 'int'})


# df2.iloc[0:6]


# print(titanic_df['survived'].dtype)

#titanic_df.groupby('sex').sum()       # wrong
#titanic_df.groupby('sex').sum(numeric_only=True )

,passengerId,pclass,name,sex,age,sibsp,parch,ticket,fare,cabin,embarked
survived,,,,,,,,,,,
0,102,102,102,102,85,102,102,102,102,14,102
1,54,54,54,54,41,54,54,54,54,17,53

In [72]:
titanic_df.groupby('sex')['survived']

# 성별에 따른 생존율 을 구함
df = titanic_df.groupby('sex')['survived'].mean( )
df

sex
female    0.714286
male      0.140000
Name: survived, dtype: float64

In [43]:
# 성별 과 생존여부로 나뉜 각 그룹의 특성 ( pclass, age, ...)
titanic_df.groupby(['sex', 'survived']).mean(numeric_only=True )

                 passengerId    pclass        age     sibsp     parch  \
sex    survived
female 0           80.437500  2.937500  20.633333  1.437500  0.562500
       1           63.200000  2.275000  26.265625  0.650000  0.500000
male   0           85.639535  2.406977  31.228571  0.523256  0.337209
       1           76.142857  2.357143  23.314444  0.142857  0.285714

                      fare
sex    survived
female 0         18.883331
       1         32.291563
male   0         28.831587
       1         22.270236

In [44]:
### data 재 구조화 하기  
##  stack  과  unstack

In [73]:
df = titanic_df.groupby(['sex', 'survived']).mean(numeric_only=True)
#df = titanic_df.groupby(['sex', 'survived']).mean(numeric_only=True)[['age']]
df

                 passengerId    pclass        age     sibsp     parch  \
sex    survived
female 0           80.437500  2.937500  20.633333  1.437500  0.562500
       1           63.200000  2.275000  26.265625  0.650000  0.500000
male   0           85.639535  2.406977  31.228571  0.523256  0.337209
       1           76.142857  2.357143  23.314444  0.142857  0.285714

                      fare
sex    survived
female 0         18.883331
       1         32.291563
male   0         28.831587
       1         22.270236

In [75]:
df.unstack('sex')

# df.unstack('survived')

         passengerId             pclass                  age             \
sex           female       male  female      male     female       male
survived
0            80.4375  85.639535  2.9375  2.406977  20.633333  31.228571
1            63.2000  76.142857  2.2750  2.357143  26.265625  23.314444

           sibsp             parch                 fare
sex       female      male  female      male     female       male
survived
0         1.4375  0.523256  0.5625  0.337209  18.883331  28.831587
1         0.6500  0.142857  0.5000  0.285714  32.291563  22.270236

In [47]:
#survived=df.unstack('survived')
#survived
survived_stack=survived.stack('survived')
survived_stack

NameError: name 'survived' is not defined

In [ ]:
###  index  초기화 하기

In [ ]:
#df
df1=df.reset_index( )
df1

In [ ]:
df.reset_index(inplace=True)
df