In [1]:
##### Section 1 : 결측치 처리
## 결측치 개념

In [2]:
import pandas as pd
url='https://raw.githubusercontent.com/sehakflower/data/main/titanic.csv'
titanic_df= pd.read_csv(url,sep='\t')
titanic_df.info( )

<class 'pandas.DataFrame'>
RangeIndex: 156 entries, 0 to 155
Data columns (total 12 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   PassengerId  156 non-null    int64
 1   Survived     156 non-null    int64
 2   Pclass       156 non-null    int64
 3   Name         156 non-null    str
 4   Sex          156 non-null    str
 5   Age          126 non-null    float64
 6   SibSp        156 non-null    int64
 7   Parch        156 non-null    int64
 8   Ticket       156 non-null    str
 9   Fare         156 non-null    float64
 10  Cabin        31 non-null     str
 11  Embarked     155 non-null    str
dtypes: float64(2), int64(5), str(5)
memory usage: 14.8 KB

In [3]:
new_columns=['passengerId', 'survived', 'pclass', 'name', 'sex', 'age', 'sibsp', 'parch',
'ticket', 'fare', 'cabin', 'embarked']
titanic_df.columns=new_columns
titanic_df.columns

Index(['passengerId', 'survived', 'pclass', 'name', 'sex', 'age', 'sibsp',
       'parch', 'ticket', 'fare', 'cabin', 'embarked'],
      dtype='str')

In [4]:
titanic_df['age'][titanic_df['age'].isna( )]

#titanic_df['age']

#titanic_df['age'].isna( )

#titanic_df[titanic_df['age'].isna()]

5     NaN
17    NaN
19    NaN
26    NaN
28    NaN
29    NaN
31    NaN
32    NaN
36    NaN
42    NaN
45    NaN
46    NaN
47    NaN
48    NaN
55    NaN
64    NaN
65    NaN
76    NaN
77    NaN
82    NaN
87    NaN
95    NaN
101   NaN
107   NaN
109   NaN
121   NaN
126   NaN
128   NaN
140   NaN
154   NaN
Name: age, dtype: float64

In [5]:
titanic_df['age'].isnull( )

#titanic_df['age'][titanic_df['age'].isnull()]

#titanic_df['age'][titanic_df['age'].isnull( )].isnull( )

#titanic_df['age'][titanic_df['age'].isnull( )].isnull().sum( )
print(titanic_df['age'][titanic_df['age'].isnull( )].isnull( ).sum( ))

30

In [6]:
titanic_df['age'].notnull( )

#titanic_df['age'][titanic_df['age'].notnull( )]

#titanic_df.loc[titanic_df['age'].notnull( ),['age', 'name']]

#titanic_df.loc[titanic_df['age'].isnull( ),['age', 'name']]

0       True
1       True
2       True
3       True
4       True
       ...
151     True
152     True
153     True
154    False
155     True
Name: age, Length: 156, dtype: bool

In [7]:
###  결측치를 다른 문자로 변경

In [11]:
# titanic_df.head( )

titanic_df['cabin']=titanic_df['cabin'].fillna('N')
titanic_df['cabin']

0         N
1       C85
2         N
3      C123
4         N
       ...
151      C2
152       N
153       N
154       N
155       N
Name: cabin, Length: 156, dtype: str

In [12]:
titanic_df['cabin'].value_counts( )

cabin
N              125
C123             2
C23 C25 C27      2
D26              2
C85              1
E46              1
G6               1
C103             1
D56              1
A6               1
B78              1
D33              1
B30              1
C52              1
B28              1
C83              1
F33              1
F G73            1
E31              1
A5               1
D10 D12          1
C110             1
B58 B60          1
E101             1
F E69            1
D47              1
B86              1
F2               1
C2               1
Name: count, dtype: int64

In [13]:
titanic_df['cabin']=titanic_df['cabin'].apply(lambda x : x[0])
titanic_df['cabin']

0      N
1      C
2      N
3      C
4      N
      ..
151    C
152    N
153    N
154    N
155    N
Name: cabin, Length: 156, dtype: str

In [14]:
#### 결측치를 평균값으로 변경하기

titanic_df_copy=titanic_df.copy( )
titanic_df_copy

,passengerId,survived,pclass,name,sex,age,sibsp,parch,ticket,fare,cabin,embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,N,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,N,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C,S
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,N,S
...,...,...,...,...,...,...,...,...,...,...,...,...
151,152,1,1,"Pears, Mrs. Thomas (Edith Wearne)",female,22.0,1,0,113776,66.6000,C,S
152,153,0,3,"Meo, Mr. Alfonzo",male,55.5,0,0,A.5. 11206,8.0500,N,S
153,154,0,3,"van Billiard, Mr. Austin Blyler",male,40.5,0,2,A/5. 851,14.5000,N,S
154,155,0,3,"Olsen, Mr. Ole Martin",male,NaN,0,0,Fa 265302,7.3125,N,S
155,156,0,1,"Williams, Mr. Charles Duane",male,51.0,0,1,PC 17597,61.3792,N,C

In [19]:
titanic_df['age']=titanic_df_copy['age'].fillna(titanic_df_copy['age'].mean())
titanic_df_copy['age']
titanic_df['age']

0      22.000000
1      38.000000
2      26.000000
3      35.000000
4      35.000000
         ...
151    22.000000
152    55.500000
153    40.500000
154    28.141508
155    51.000000
Name: age, Length: 156, dtype: float64

In [ ]:
####  DataFrame 의 복사 
## shallow copy  /   deep copy

In [21]:
copy_titanic_df=titanic_df.copy( )
copy_titanic_df

,passengerId,survived,pclass,name,sex,age,sibsp,parch,ticket,fare,cabin,embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.000000,1,0,A/5 21171,7.2500,N,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.000000,1,0,PC 17599,71.2833,C,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26.000000,0,0,STON/O2. 3101282,7.9250,N,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.000000,1,0,113803,53.1000,C,S
4,5,0,3,"Allen, Mr. William Henry",male,35.000000,0,0,373450,8.0500,N,S
...,...,...,...,...,...,...,...,...,...,...,...,...
151,152,1,1,"Pears, Mrs. Thomas (Edith Wearne)",female,22.000000,1,0,113776,66.6000,C,S
152,153,0,3,"Meo, Mr. Alfonzo",male,55.500000,0,0,A.5. 11206,8.0500,N,S
153,154,0,3,"van Billiard, Mr. Austin Blyler",male,40.500000,0,2,A/5. 851,14.5000,N,S
154,155,0,3,"Olsen, Mr. Ole Martin",male,28.141508,0,0,Fa 265302,7.3125,N,S
155,156,0,1,"Williams, Mr. Charles Duane",male,51.000000,0,1,PC 17597,61.3792,N,C

In [22]:
#hex(id(titanic_df)), hex(id(copy_titanic_df))

id(titanic_df), id(copy_titanic_df)

(4583515072, 4740503376)

In [23]:
###  여기서 잠시 identical ,   equal   의   의미는?
### identical
 
a = 256
b = 256
print (a is b), print(id(a) == id(b)), print(a == b)

a = 259
b = 259
print (a is b), print(id(a) == id(b)), print(a == b)

True
True
True
False
False
True

(None, None, None)

In [ ]:
copy_titanic_df['age']=0
copy_titanic_df.head( )['age'],   titanic_df.head()['age']

In [ ]:
a = ['a',2,3, 500]
b = a.copy()

id(a[0]), id(b[0])

# a[0] = 'kk'

# id(a[0]), id(b[0])

# a[0], b[0]

In [ ]:
##### data 형 변환

In [ ]:
###  to_numeric
titanic_df1=titanic_df[['survived', 'pclass', 'name', 'sex', 'age', 'sibsp', 'parch', 'fare']]
titanic_df2=titanic_df1.apply(pd.to_numeric, errors='coerce')      # coerce:   에러가 나오면 강제로 결측치 (NaN) 로 만들어라.
titanic_df2

In [ ]:
titanic_df2.dtypes

In [ ]:
#####   astype 함수
titanic_df2['survived']=titanic_df2['survived'].astype('float')
titanic_df2['pclass']=titanic_df2['pclass'].astype('float')
titanic_df2['age']=titanic_df2['age'].astype('float')
titanic_df2['sibsp']=titanic_df2['sibsp'].astype('float')
titanic_df2['parch']=titanic_df2['parch'].astype('float')
titanic_df2['fare']=titanic_df2['fare'].astype('float')
titanic_df2.dtypes

In [ ]:
titanic_df1=titanic_df[['survived', 'pclass', 'name', 'sex', 'age', 'sibsp', 'parch', 'fare']]
# tmp=[]
# for each in titanic_df1['sex']:
#  if each=='female':
#   tmp.append(0)
#  else:
#   tmp.append(1)
  
# titanic_df1['gender']=tmp
# titanic_df1


# titanic_df1['gender2']=[1 if x == 'female' else 0 for x in titanic_df['sex']]
# titanic_df1

# #'female'은 1, 'male'은 0으로 바꾸고 나머지는 모두 NaN 처리
# titanic_df1['gender2'] = titanic_df['sex'].map({'female': 1, 'male': 0})
# titanic_df1

# import numpy as np
# # female은 1로, 나머지는 그대로(NaN 포함) 두거나 나중에 처리
# titanic_df1['gender2'] = titanic_df['sex'].apply(lambda x: 1 if x == 'female' else (0 if x == 'male' else np.nan))
# titanic_df1

# import numpy as np
# titanic_df1['gender2'] = np.where(titanic_df['sex'] == 'female', 1, 0)
titanic_df1

In [ ]:
#
titanic_df1.drop(columns='sex', inplace=True)
titanic_df1.head( )

In [ ]:
### 문자형 변수 변환
condition=lambda x: x.split(',')[1].split('.')[0].strip( )
titanic_df1['title']=titanic_df1['name'].map(condition)
titanic_df1.head()

# titanic_df1['title'].unique( ) 

# titanic_df1[titanic_df1['title'] == 'Master']
# master_df = titanic_df1.query("title == 'Master'")

# master_df = titanic_df1.loc[titanic_df1['title'] == 'Master', :]
master_df = titanic_df1.loc[titanic_df1['title'].str.contains('Master'), :]


#master_df = titanic_df1[titanic_df1['title'].str.contains('Master')]


master_df

In [ ]:
Special=['Master', 'Don', 'Rev']
for each in Special:
  titanic_df1['title']=titanic_df1['title'].replace(each, 'Special')
  
titanic_df1['title'].unique( )
titanic_df1


### apply 을 이용해서 해 보면
# titanic_df1['title'] = titanic_df1['title'].apply(lambda x: 'Special' if x=='Master' or x=='Don' or x=='Rev' else x)
# titanic_df1.head(10)


#titanic_df1[titanic_df1['title'] == 'Special']

In [ ]:
titanic_df1=titanic_df1.drop('name', axis=1)
titanic_df1

In [ ]:
def convert_title(x):
  if x=="Special":
    return 1
  else:
    return 0

titanic_df1["special_title"]=titanic_df1["title"].apply(convert_title)
titanic_df1.tail(7)

In [ ]:
titanic_df1.drop('title', axis=1, inplace=True)
titanic_df1

In [ ]:
titanic_df1['sibpar']=titanic_df1['sibsp']+titanic_df1['parch']
titanic_df1

In [ ]:
titanic_df1.drop(['sibsp','parch'], axis =1, inplace=True)

#titanic_df1['avgfare']=titanic_df1['fare']/titanic_df1['sibpar']
titanic_df1

In [ ]:
titanic_df1['n_family1']=[1 if i==0 else i+1 for i in titanic_df1['sibpar']]
titanic_df1

In [ ]:
titanic_df1.rename(columns={'gender':'sex', 'special_title':'title', 'avgfare':'fare', 'n_family':'num_family'}, inplace=True)
titanic_df1

In [ ]:
#titanic_df1=titanic_df1.dropna( )
titanic_df1.info( )

In [ ]:
rows_with_nan = titanic_df1[titanic_df1.isnull().any(axis=1)]
#rows_with_nan = titanic_df1[~titanic_df1.isnull().any(axis=1)]
#age_nan_rows = titanic_df1[titanic_df1['age'].isnull()]
rows_with_nan

In [ ]:
titanic_df1=titanic_df1.dropna( )     # 결측치가 하나라도 있으면 삭제
titanic_df1.info( )

#### Pandas 의 통계 함수

In [ ]:
titanic_df.describe( )

In [ ]:
titanic_df.sum( )

titanic_df.count( )

titanic_df.min( ) , titanic_df.max( )

In [ ]:
titanic_df.mean(numeric_only=True )              # 평균
#titanic_df.median( numeric_only=True)            # 중앙값
titanic_df.mode( )                                  # 가장 빈번하게 나타 나는 값 (최빈값.   0번째 row 에 나타남)
#titanic_df.head(40)

In [ ]:
### 편차 구하기 (Deviation:   관측치 - 평균)
#titanic_df.mad()    #  deprecated 됨.  Mean Absolute Deviation

titanic_df.std(numeric_only=True)

#titanic_df['age'] - titanic_df['age'].mean()

In [ ]:
def normalize(df):
    """데이터를 0~1 사이 값으로 정규화합니다."""
    return (df - df.min()) / (df.max() - df.min())

# 정규 화(Min-Max Scaling) - 데이타를 0과 1사이의 값으로 압축.  기본 분포 그대로 유지 되도록 함.
#  y =   ( x - mean ) / (max - min)
titanic_df['age_norm'] = normalize(titanic_df['age'])
titanic_df

In [ ]:
def standardize(df):
    """평균 0, 표준편차 1이 되도록 표준화합니다."""
    return (df - df.mean()) / df.std()

# 표준화 (Z-score scaling) - 평균을 0, 표준편차를 1로 변환.   표준 정규 분포를 따르도록 유도.  데이타가 정규분포를 따를때
#  y = (x - mean) / 표준편차
titanic_df['age_std'] = standardize(titanic_df['age'])
titanic_df

###  분산 구하기:  var
## .var() :   sigma ** 2    분산
## .std() :  sigma   표준 편차   
## 
## 분산(variance) 과 표준편차(standard deviation) 는 각각 중심에서 얼마나 떨어져 있는지를 나타내는 지표
## variance:  원래 데이터의 제곱 단위  (x - mean) ** 2,  ==   sigma ** 2 .    수학적으로 다루기 쉬움. 머신 러닝 에서 미분 등..
## std:  원래 데이터의 단위 :   sqrt(variance) == sigma

## std: 중심값에서 떨어진 정도  
## 1sigma: 전체 데이터의 68% 정도가 mean 을 중심으로 그 안에 있슴 ,    2sigma: 중심값에서 95%,  3sigma:  중심값에서 99.7%  

## surviced std: 0.477275 의 해석
## 이진 데이터 (1, 0) 의 std 는 넓게 퍼진 정도가 아니라 데이터가 한쪽으로 쏠린 정도를 나타냄.   이 경우는 0.5 근처에

In [ ]:
import numpy as np
import matplotlib.pyplot as plt
from scipy.stats import norm

# 1. 데이터 준비 (표준정규분포)
mu, sigma = 0, 1
x = np.linspace(-4, 4, 1000)
y = norm.pdf(x, mu, sigma)

plt.figure(figsize=(10, 6))
plt.plot(x, y, 'black', lw=2)

# 2. 각 구간 색칠하기 (중첩되므로 투명도 조절이 중요)
# 99.7% 영역 (3 sigma)
plt.fill_between(x, y, where=(x >= -3) & (x <= 3), color='lightgray', alpha=0.3, label='99.7% (3$\sigma$)')
# 95% 영역 (2 sigma)
plt.fill_between(x, y, where=(x >= -2) & (x <= 2), color='skyblue', alpha=0.4, label='95.0% (2$\sigma$)')
# 68% 영역 (1 sigma)
plt.fill_between(x, y, where=(x >= -1) & (x <= 1), color='royalblue', alpha=0.6, label='68.0% (1$\sigma$)')

# 3. 그래프 꾸미기
plt.title('Empirical Rule: 68-95-99.7', fontsize=15)
plt.xlabel('Standard Deviations ($\sigma$)', fontsize=12)
plt.ylabel('Probability Density', fontsize=12)
plt.xticks([-3, -2, -1, 0, 1, 2, 3])
plt.legend()
plt.grid(axis='y', alpha=0.3)

plt.show()

In [ ]:
#titanic_df.var(numeric_only=True), titanic_df.std(numeric_only=True)

#titanic_df.describe()

In [ ]:
## 왜도 (skewness):   데이터가 어느 한쪽으로 치우쳤는가의 정도
##  0 에 가까움:  평균/중앙값/최빈값 이 거의 일치 함.  좌우 대칭
## + 값: 오른쪽으로 꼬리가 김
## - 값: 왼쪽으로 꼬리가 김

## 꼬리가 길게 치우쳐 있다는 뜻은 대부분의 사람들은 그 반대 편에 위치 한다는 뜻.   즉, 꼬리가 오른쪽으로 길면 왼쪽 부분이 다수 라는 뜻

## pclass:   3 등석에 몰려 있슴 (1 / 2 / 3 등석)
## fare:  요금이 오른쪽에 몰려 있슴 (비싼 요금)
titanic_df.skew(numeric_only=True )

In [ ]:
#titanic_df['survived'].value_counts()
#survived_count = titanic_df['survived'].sum()
#titanic_df

In [ ]:
import seaborn as sns
import matplotlib.pyplot as plt

# Fare(요금)의 치우침 확인
sns.displot(titanic_df['fare'], kde=True)
plt.title(f"Fare Skewness: {titanic_df['fare'].skew():.2f}")
plt.show()

In [ ]:
import seaborn as sns
import matplotlib.pyplot as plt

# Fare(요금)의 치우침 확인
sns.displot(titanic_df['age'], kde=True)
plt.title(f"Fare Skewness: {titanic_df['fare'].skew():.2f}")
plt.show()

In [ ]:
###  첨도(kurtosis):   뾰쪽한 정도.   얼마나 중앙에 몰려 있나.  표준편차에서는 0 이 중앙
##  첨도가 높을 수록 데이터가 평균 근처에 아주 빽빽하게 모여 있고, 동시에 아주 멀리 떨어진 극단적인 값(이상치)이 존재한다는 뜻입니다. (예: 500달러가 넘는 요금)
##  첨도가 낮을 수록 데이터가 중앙에 있지 않고 아주 넓게 퍼져 있슴

# survived 는 0 / 1  이라서 중앙이 비어 있슴.  낮은 첨도
# age:  그래도 0 보다 좀 커서 대체로 중앙값에 어느 정도 몰려 있슴
# parch:  아주 높은 밀도로 중앙에 몰려 있슴. (대부분 가족 없이 탑승)
# fare: 아주 멀리 떨어진 극단적인 값(이상치) (outliers)이 존재한다는 뜻입니다. (예: 500달러가 넘는 요금)

titanic_df.kurt(numeric_only=True)

In [ ]:
###
# sibsp(sibling/spouses):  형제/자매/배우자의 수   1 이라면 형제/자매/배우자 중 1명과 같이 탐
# parch(parents/children)

# 가족 총 인원수 파생 변수 만들기
titanic_df['FamilySize'] = titanic_df['sibsp'] + titanic_df['parch'] + 1

# 혼자 온 사람(Alone) 여부 확인
titanic_df['IsAlone'] = (titanic_df['FamilySize'] == 1).astype(int)

titanic_df.head(10)

In [ ]:
### 특정 열(column)의  통계치

titanic_df['age'].max(), titanic_df['age'].min(), titanic_df['age'].sum()

#titanic_df['age'].count(), titanic_df['age'].mean()

In [ ]:
titanic_df['age'].std() , titanic_df['age'].median()

#titanic_df['age'].mode()   # 최빈값